# Generated by Django 5.1.1 on 2024-09-19 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='surname',
        ),
        migrations.AddField(
            model_name='group',
            name='contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='course_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='group',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='courses/course_photo/%Y/%m'),
        ),
        migrations.AddField(
            model_name='group',
            name='max_student',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='start_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.groupspec'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='professors/profile_photo'),
        ),
        migrations.AlterField(
            model_name='group',
            name='lang',
            field=models.CharField(choices=[('1', 'UZ'), ('2', 'RU'), ('3', 'EN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.skill'),
        ),
    ]
