# Generated by Django 5.0.7 on 2024-09-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
