# Generated by Django 5.1.1 on 2024-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplikes',
            name='user',
        ),
        migrations.AddField(
            model_name='grouplikes',
            name='session_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
