# Generated by Django 5.1.1 on 2024-09-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_options_teacher_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='dj_group',
        ),
    ]
