# Generated by Django 5.1.1 on 2024-09-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_skill_remove_teacher_surname_group_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
