# Generated by Django 5.1.1 on 2024-09-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='surname',
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.groupspec'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='professors/profile_photo'),
        ),
    ]
