# Generated by Django 5.1.1 on 2024-09-26 19:35

import django.db.models.deletion
import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_options_alter_lesson_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=teacher.models.lesson_file_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.lessonfiles'),
        ),
    ]
