# Generated by Django 5.1.1 on 2024-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_student_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skills',
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.ManyToManyField(to='teacher.skill'),
        ),
    ]
