# Generated by Django 5.1.1 on 2024-09-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teacher', '0005_alter_teacher_address_remove_teacher_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dj_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
