# Generated by Django 5.1.1 on 2024-09-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_lessonfiles_alter_lesson_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.ManyToManyField(null=True, to='teacher.lessonfiles'),
        ),
    ]
