# Generated by Django 5.1.1 on 2024-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_lesson_file_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.lessonfiles'),
        ),
    ]
