# Generated by Django 5.1.1 on 2024-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_lesson_file_lessonfiles_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonfiles',
            options={'verbose_name_plural': 'LessonFiles'},
        ),
    ]
