# Generated by Django 5.1.1 on 2024-09-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_skill_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
