# Generated by Django 5.1.1 on 2024-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_lessonfiles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_attendance',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
