# Generated by Django 5.1.1 on 2024-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_score_attendance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_attendance',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
