# Generated by Django 5.1.1 on 2024-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_alter_score_attendance_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score_attendance',
            name='was_present',
        ),
        migrations.AddField(
            model_name='score_attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='score_attendance',
            name='mark',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True),
        ),
    ]
