# Generated by Django 5.1.1 on 2024-09-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_student_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='courses/course_photo/%Y/%m'),
        ),
    ]
