# Generated by Django 5.1.1 on 2024-09-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_remove_score_attendance_was_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_attendance',
            name='lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.lesson'),
        ),
        migrations.AlterField(
            model_name='score_attendance',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='score_attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.student'),
        ),
    ]
