# Generated by Django 5.1.1 on 2024-09-28 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_score_attendance_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_attendance',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
