# Generated by Django 5.1.1 on 2024-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_deparment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deparment',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
