# Generated by Django 5.1.1 on 2024-09-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_deparment_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deparment',
        ),
    ]
