# Generated by Django 5.1.1 on 2024-10-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_remove_lesson_group_lesson_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.group'),
        ),
    ]
