# Generated by Django 5.1.1 on 2024-10-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_remove_lesson_group_lesson_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ManyToManyField(to='teacher.group'),
        ),
    ]
